PCS1/Controllers/PcsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PCS1.Models;
using PCS1.Repositories;
using PCS1.ViewModel;
using PagedList;
using System.Web.Script.Serialization;
using System.Web;

namespace PCS1.Controllers
{
    public class PcsController : Controller
    {
        Encrypt_Decrypt ed = new Encrypt_Decrypt();
        dbpcsEntities db = new dbpcsEntities();
        //Property of the type IRepository <TEnt, in TPk>
        private IRepository<tbl_User, int,string > _repository;
        private ICalendarRepository<tbl_Patient, long> _calrepository;
        private ISettings<tbl_Settings> _settingsrepository;
        static string ln,st;
        static int? packaging=0;
        static DateTime? fd, td;
        public PcsController(IRepository<tbl_User, int,string> repo, ICalendarRepository<tbl_Patient, long> prepo,ISettings<tbl_Settings> srepo)
        {
            _repository = repo;
            _calrepository = prepo;
            _settingsrepository = srepo;
        }
        // GET: Pcs/UserLogin
        public ActionResult Login()
        {
            return View();
        }
        // POST: Pcs/UserLogin
        [HttpPost]
        public ActionResult Login(UserLogin User)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tbl_User usr = new tbl_User();
                    usr.Username = User.Username;
                    usr.Password = User.Password;
                    var user = _repository.LoginUser(usr);
                    tbl_Admin Admin = new tbl_Admin();
                    Admin.UserName = User.Username;
                    Admin.Password = User.Password;
                    var password = ed.Encrypt(Admin.Password);
                    var admin = db.tbl_Admin.Where(p => p.UserName.ToUpper() == Admin.UserName.ToUpper() && p.Password == password).FirstOrDefault();                    
                    if (user != null)
                    {
                        Session["User"] = user.Email;
                        HttpCookie UserDetailsCookie = new HttpCookie("LoggedInUser");
                        UserDetailsCookie.Name = "LoggedInUser";
                        UserDetailsCookie.Expires = DateTime.MaxValue;
                        UserDetailsCookie.Values.Add("UserName", user.Email);                       
                        Response.Cookies.Set(UserDetailsCookie);
                        Session["User"] = user.Email;
                        return RedirectToAction("Calendar");
                    }
                    else if(admin != null)
                    {
                        Session["Admin"] = admin.Email;
                        return RedirectToAction("MyProfile","Admin");
                    }
                    else
                    {
                        TempData["LoginMessage"] = "Wrong Username/Password";
                        return View(User);
                    }
                }
                else
                    return View();
        }
            catch
            {
                return View();
    }
}
        // GET: Pcs/UserRegister
        public ActionResult ChangePassword()
        {
            try
            {
                if (Session["User"] != null)
                {
                    var user = new ChangePassword();
                    user.Email = Session["User"].ToString();
                    return View(user);
                }
                else
                    return RedirectToAction("Login");
            }
            catch
            {
                return View();
            }
}
        // POST: Pcs/UserRegister
        [HttpPost]
        public ActionResult ChangePassword(ChangePassword User)
        {
            try
            {
                if (Session["User"] != null)
                {
                    if (ModelState.IsValid)
                    {
                        tbl_User usr = new Models.tbl_User();
                        usr.Email = Session["User"].ToString();
                        usr.Password = User.Password;
                        usr.NewPassword = User.NewPassword;
                        User.Email = usr.Email;
                        bool chk = _repository.ChangePassword(usr);
                        if (chk == true)
                        {
                            TempData["CPMessage"] = "Password Changed Successfully";
                            return View(User);
                        }
                        else
                        {
                            TempData["CPMessage"] = "Something Went Wrong";
                            return View(User);
                        }
                    }
                    else
                        return View(User);
                }
                else
                    return RedirectToAction("Login");               
            }

            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                          validationErrors.Entry.Entity.ToString(),
                       validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
        }
        // GET: Pcs Calendar
        public ActionResult Calendar()
        {
            //if (Session["User"] != null)
            //{
            HttpCookie UserDetailsCookie = Request.Cookies["LoggedInUser"];
            if (UserDetailsCookie != null)
            {
                Session["User"] = UserDetailsCookie["UserName"];
            }
            return View();
            //}
            //else
            //    return RedirectToAction("Login");
        }
        [HttpPost]
        public ActionResult Calendar(string command, tbl_Patient entity,DateTime? date3)
        {
            try
            {
                //if (Session["User"] != null)
                //{
                    if (command == "Update")
                        _calrepository.EditPatients(entity, entity.Patient_Id);
                    else if (command == "Delete")
                        _calrepository.RemovePatients(entity);
                    else if (command == "Stop")
                        _calrepository.StopPatients(entity, entity.Patient_Id);
                    else if (command == "PrintShipping")
                    {
                    Session["selecteddate"] = date3.Value.ToShortDateString();
                        List<tbl_Patient> patientList = null;
                        patientList = _calrepository.GetPatients().Where(p=>p.CycleDate==date3.Value).OrderBy(p => p.LastName).ToList();
                        var builder = new PdfBuilder(patientList, Server.MapPath("/PCS/Views/Pcs/ConvertToPdfSelected.cshtml"), Server.MapPath("/PCS/Content/Site.css"));
                        return builder.GetPdf1();
                }
                else if (command == "PrintBilling")
                {
                    Session["selecteddate"] = date3.Value.ToShortDateString();
                    List<tbl_Patient> patientList = null;
                    patientList = _calrepository.GetPatients().Where(p => p.BillingCycleStartDate == date3.Value).OrderBy(p => p.LastName).ToList();
                    var builder = new PdfBuilder(patientList, Server.MapPath("/PCS/Views/Pcs/ConvertToPdfSelectedBilling.cshtml"), Server.MapPath("/PCS/Content/Site.css"));
                    return builder.GetPdf1();
                }
                return View();
                //}
                //else
                //{
                //    return RedirectToAction("Login");
                //}
        }
            catch(Exception ex)
            {
                return View();
    }
}
        public long getselfid()
        {
            long id = 0;
            var getlist = _calrepository.GetPatients();
            if (getlist.Count() == 0)
                id = 1;
            else
            {
                long maxid = getlist.Max(p => p.SelfKey_Id).Value;
                id = ++maxid;
            }
            return id;
        }
        // GET: Pcs/getPatients
        public ActionResult getPatients()
        {
            try
            {
                List<PatientDetails> PatientList = new List<PatientDetails>();
                var patientList = _calrepository.GetPatients().Where(p=>p.BillingCycleStartDate!=null).ToList();
                bool a = true;
                ranges rg = new ranges();
                List<ranges> lstrng = new List<ranges>();                      
                foreach (var q in patientList)
                {                   
                    if (a == true)
                    {
                        var settings = _settingsrepository.GetSettings();
                        foreach (var st in settings)
                        {
                            if (st.key_id == "StartDate")
                                rg.start = st.key_date.ToString();
                            if (st.key_id == "EndDate")
                                rg.end = st.key_date.ToString();
                        }
                        lstrng.Add(rg);
                        a = false;
                    }                
                    PatientDetails pd = new PatientDetails();
                    pd.id = Convert.ToString(q.Patient_Id);
                    pd.title = q.FirstName + " " + q.LastName;

PCS1/Views/Pcs/ConvertToPdf.cshtml
@using PCS1.Models
@model IEnumerable<PCS1.Models.tbl_Patient>

@{
    ViewBag.Title = "ConvertToPdf";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="witdh=device-witdh" />
    <title>Shipping List</title>
    <style>
        th{
            padding:0px 6px 20px 0px;                       
        }
        td{
            padding:0px 6px 25px 0px;
        }
    </style>
</head>
<body>
    <div>
      
        <h4>Shipping List ( @System.Web.HttpContext.Current.Session["fromdate"].ToString()  @System.Web.HttpContext.Current.Session["todate"].ToString() )
        </h4>
        <hr />
        <table class="table" >
            <tr>
                <th>
                   <label>First Name</label>
                </th>
                <th>
                    <label>Last Name</label>                    
                </th>             
                <th>
                    <label>Cycle</label>                      
                </th>
                <th>
                   <label>Packaging</label>
                </th>
                <th>
                    <label>State</label>                      
                </th>
                <th>
                    <label>F</label>
                </th>
                <th>
                    <label>T</label>
                </th>
                <th>
                    <label>P</label>
                </th>
                <th>
                    <label>S</label>
                </th>
            </tr>
            
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.FirstName
                    </td>
                    <td>
                        @item.LastName
                    </td>                  
                    <td>
                        @if (item.CycleType == 1)
                        {<span>  Weekly </span>}
                        else if (item.CycleType == 2)
                        {  <span>Bi-Weekly</span>}
                        else if (item.CycleType == 3)
                        {  <span>Monthly</span>}
                        else if (item.CycleType == 4)
                        { <span>12 Weeks</span>}
                        
                    </td>
                    <td>
                        @if (item.PackagingType == 0)
                        {  <span>None</span>}
                        else if (item.PackagingType == 1)
                        {<span>Trays</span>}
                        else if (item.PackagingType == 2)
                        {<span>Blister</span>}
                        else if (item.PackagingType == 3)
                        {<span>Vials</span>}
                        else
                        {<span>-</span>}
                    </td>
                    <td>
                        @if (item.State != null && item.State != "0")
                        { @item.State}
                        else
                        { <span>-</span>}
                    </td>
                    <td>
                        <span>F _____</span>
                    </td>
                    <td>
                        <span>T _____</span>
                    </td>
                    <td>
                        <span>P _____</span>
                    </td>
                    <td>
                        <span>S _____</span>
                    </td>
                </tr>
            }

        </table>
    </div>

</body>
</html>

PCS1/Views/Pcs/ConvertToPdfBilling.cshtml
@using PCS1.Models
@model IEnumerable<PCS1.Models.tbl_Patient>

@{
    ViewBag.Title = "ConvertToPdf";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="witdh=device-witdh" />
    <title>Billing List</title>
    <style>
        th{
            padding:0px 8px 20px 0px;                       
        }
        td{
            padding:0px 8px 25px 0px;
        }
    </style>
</head>
<body>
    <div>
      
        <h4>Billing List ( @System.Web.HttpContext.Current.Session["fromdate"].ToString()  @System.Web.HttpContext.Current.Session["todate"].ToString() )
        </h4>
        <hr />
        <table class="table" >
            <tr>
                <th>
                   <label>First Name</label>
                </th>
                <th>
                    <label>Last Name</label>                    
                </th>   
                <th>
                    <label>Billing Start Date</label>
                </th>              
                <th>
                    <label>Cycle</label>                      
                </th>
                <th>
                    <label>Billing Cycle</label>
                </th>
                <th>
                    <label>Packaging</label>
                </th>
                <th>
                    <label>State</label>                      
                </th>
             
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.FirstName
                    </td>
                    <td>
                        @item.LastName
                    </td>   
                    <td>
                        @item.BillingCycleStartDate.Value.ToShortDateString()
                    </td>                
                    <td>
                        @if (item.CycleType == 1)
                        {<span>  Weekly </span>}
                        else if (item.CycleType == 2)
                        {  <span>Bi-Weekly</span>}
                        else if (item.CycleType == 3)
                        {  <span>Monthly</span>}
                        else if (item.CycleType == 4)
                        { <span>12 Weeks</span>}
                        
                    </td>
                    <td>
                        @if (item.BillingCycle == 1)
                {<span>4 Weeks </span>}
                else if (item.BillingCycle == 2)
                { <span>12 Weeks</span>}
                else
                { <span>-</span>}
                    </td>
                    <td>
                        @if (item.PackagingType == 0)
                        {  <span>None</span>}
                        else if (item.PackagingType == 1)
                        {<span>Trays</span>}
                        else if (item.PackagingType == 2)
                        {<span>Blister</span>}
                        else if (item.PackagingType == 3)
                        {<span>Vials</span>}
                        else
                        {<span>-</span>}
                    </td>
                    <td>
                        @if (item.State != null && item.State != "0")
                        { @item.State}
                        else
                        { <span>-</span>}
                    </td>
                  
                </tr>
            }

        </table>
    </div>

</body>
</html>

PCS1/Views/Pcs/ConvertToPdfSelected.cshtml
@using PCS1.Models
@model IEnumerable<PCS1.Models.tbl_Patient>

@{
    ViewBag.Title = "ConvertToPdfSelected";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="witdh=device-witdh" />
    <title>Shipping List</title>
    <style>
        th{
            padding:0px 6px 20px 0px;                       
        }
        td{
            padding:0px 6px 25px 0px;
        }
    </style>
</head>
<body>
    <div>
      
        <h4>Shipping List ( @System.Web.HttpContext.Current.Session["selecteddate"].ToString() )
        </h4>
        <hr />
        <table class="table" >
            <tr>
                <th>
                   <label>First Name</label>
                </th>
                <th>
                    <label>Last Name</label>                    
                </th>             
                <th>
                    <label>Cycle</label>                      
                </th>
                <th><label>Packaging</label></th>
                <th>
                    <label>State</label>                      
                </th>
                <th>
                    <label>F</label>
                </th>
                <th>
                    <label>T</label>
                </th>
                <th>
                    <label>P</label>
                </th>
                <th>
                    <label>S</label>
                </th>
            </tr>
            
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.FirstName
                    </td>
                    <td>
                        @item.LastName
                    </td>                  
                    <td>
                        @if (item.CycleType == 1)
                        {<span>  Weekly </span>}
                        else if (item.CycleType == 2)
                        {  <span>Bi-Weekly</span>}
                        else if (item.CycleType == 3)
                        {  <span>Monthly</span>}
                        else if (item.CycleType == 4)
                        { <span>12 Weeks</span>}
                        
                    </td>
                    <td>
                        @if (item.PackagingType == 0)
                        {  <span>None</span>}
                        else if (item.PackagingType == 1)
                        {<span>Trays</span>}
                        else if (item.PackagingType == 2)
                        {<span>Blister</span>}
                        else if (item.PackagingType == 3)
                        {<span>Vials</span>}
                        else
                        {<span>-</span>}
                    </td>
                    <td>
                        @if (item.State != null && item.State != "0")
                        { @item.State}
                        else
                        { <span>-</span>}
                    </td>
                    <td>
                        <span>F _____</span>
                    </td>
                    <td>
                        <span>T _____</span>
                    </td>
                    <td>
                        <span>P _____</span>
                    </td>
                    <td>
                        <span>S _____</span>
                    </td>
                </tr>
            }

        </table>
    </div>

</body>
</html>

PCS1/Views/Pcs/ConvertToPdfSelectedBilling.cshtml
@using PCS1.Models
@model IEnumerable<PCS1.Models.tbl_Patient>

@{
    ViewBag.Title = "ConvertToPdfSelectedBilling";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="witdh=device-witdh" />
    <title>Billing List</title>
    <style>
        th{
            padding:0px 6px 20px 0px;                       
        }
        td{
            padding:0px 6px 25px 0px;
        }
    </style>
</head>
<body>
    <div>
      
        <h4>Billing List ( @System.Web.HttpContext.Current.Session["selecteddate"].ToString() )
        </h4>
        <hr />
        <table class="table">
            <tr>
                <th>
                    <label>First Name</label>
                </th>
                <th>
                    <label>Last Name</label>
                </th>
                <th>
                    <label>Billing Start Date</label>
                </th>
                <th>
                    <label>Cycle</label>
                </th>
                <th>
                    <label>Billing Cycle</label>
                </th>
                <th>
                    <label>Packaging</label>
                </th>
                <th>
                    <label>State</label>
                </th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.FirstName
                    </td>
                    <td>
                        @item.LastName
                    </td>
                    <td>
                        @item.BillingCycleStartDate.Value.ToShortDateString()
                    </td>
                    <td>
                        @if (item.CycleType == 1)
                        {<span>  Weekly </span>}
                        else if (item.CycleType == 2)
                        {  <span>Bi-Weekly</span>}
                        else if (item.CycleType == 3)
                        {  <span>Monthly</span>}
                        else if (item.CycleType == 4)
                        { <span>12 Weeks</span>}

                    </td>
                    <td>
                        @if (item.BillingCycle == 1)
                {<span>4 Weeks </span>}
                else if (item.BillingCycle == 2)
                { <span>12 Weeks</span>}
                else
                { <span>-</span>}
                    </td>
                    <td>
                        @if (item.PackagingType == 0)
                        {  <span>None</span>}
                        else if (item.PackagingType == 1)
                        {<span>Trays</span>}
                        else if (item.PackagingType == 2)
                        {<span>Blister</span>}
                        else if (item.PackagingType == 3)
                        {<span>Vials</span>}
                        else
                        {<span>-</span>}
                    </td>
                    <td>
                        @if (item.State != null && item.State != "0")
                        { @item.State}
                        else
                        { <span>-</span>}
                    </td>

                </tr>
            }

        </table>
    </div>

</body>
</html>

PCS1/Views/Pcs/Login.cshtml
@using PCS1.Models
@model PCS1.ViewModel.UserLogin

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/LoginShared.cshtml";
}

            <div class="col-md-4"></div>
            <div class="col-md-4">
                <section class="login-form">
                    <form role="login" method="post">                        
                        <img src="~/Images/medminder-logo1.png" class="img-responsive" alt="" />
                       
                        @*<div class="pwstrength_viewport_progress"></div>*@
                        <div class="form-group">
                            @*@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <div class="col-md-12">
                                @Html.TextBoxFor(model => model.Username, new { @class = "form-control input-lg",@placeholder="Username" })
                                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @*@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <div class="col-md-12">
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control input-lg", @placeholder = "Password" })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button>
                        <div>
                            <a href="@getpath.getallpath/admin/ForgetPassword">Forget Password</a>
                        </div>
                     </form>                  
                </section>
            </div>
            <div class="col-md-4"></div>

@if (TempData["LoginMessage"] != null)
{
    <div id="myModal" class="modal hide fade modalErrorMsg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">
        <div class="modal-body" style="">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <p>@TempData["LoginMessage"]</p>
        </div>
    </div>
}

PCS1/Views/Pcs/Register.cshtml
@model PCS1.Models.tbl_User
@using PCS1.Models
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/MasterShared.cshtml";
}

   
        @Html.AntiForgeryToken()      
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <section class="login-form">
                      @using (Html.BeginForm("Register", "Pcs", FormMethod.Post, new { @role = "login" }))
                      {
                            <h4>Register</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control input-lg", @placeholder = "First Name" })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger"})
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.LastName,  new { @class = "form-control input-lg", @placeholder = "Last Name" })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.ContactNo, new  { @class = "form-control input-lg", @placeholder = "Contact No" } )
                                    @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control input-lg", @placeholder = "Email" })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger"  })
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-12">
                                    @Html.PasswordFor(model => model.Password,  new { @class = "form-control input-lg", @placeholder = "Password" })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger"  })
                                </div>
                            </div>
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-12">
                                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control input-lg", @placeholder = "ConfirmPassword" })
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input type="submit" value="Register" class="btn btn-lg btn-primary btn-block" />
                                </div>
                            </div>
                                 <div>
                            <a href="@getpath.getallpath/Login">Back To Login</a>
                            </div>
                                
                                    }
</section>
                </div>           
   

@if (TempData["RegisterMessage"] != null)
{

    <div id="myModal" class="modal hide fade modalErrorMsg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">
        <div class="modal-body" style="">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <p>@TempData["RegisterMessage"]</p>
        </div>

    </div>

}
  